export const countryData = {
  portugal: {
    name: "Portugal",
    flag: "🇵🇹",
    code: "PT",
    region: "Europe",
    cities: ["Lisbon", "Porto", "Algarve", "Madeira", "Cascais"],
    visaTypes: ["D7 Passive Income Visa", "NHR Tax Regime", "Digital Nomad Visa", "Golden Visa"],
    costRange: { min: 1800, max: 3500 },
    safetyRating: 9.2,
    healthcareQuality: 8.5,
    expatFriendliness: 9.4,
    climate: "mild",
    language: "Portuguese (English widely spoken)",
    internetSpeed: "Fast",
    taxFriendly: true,
    highlights: ["EU access", "Low crime", "Great food & wine", "NHR tax benefits"],
    challenges: ["Housing costs rising", "Bureaucracy", "Language barrier outside cities"],
    avgTemp: "18°C / 64°F",
    timeZone: "WET (UTC+0/+1)",
  },
  spain: {
    name: "Spain",
    flag: "🇪🇸",
    code: "ES",
    region: "Europe",
    cities: ["Barcelona", "Madrid", "Valencia", "Seville", "Málaga"],
    visaTypes: ["Non-Lucrative Visa", "Digital Nomad Visa", "Golden Visa", "Entrepreneur Visa"],
    costRange: { min: 2000, max: 4000 },
    safetyRating: 8.8,
    healthcareQuality: 8.9,
    expatFriendliness: 8.7,
    climate: "warm",
    language: "Spanish (some English in cities)",
    internetSpeed: "Fast",
    taxFriendly: false,
    highlights: ["Mediterranean lifestyle", "Excellent food", "Rich culture", "EU access"],
    challenges: ["Higher taxes", "Slow bureaucracy", "Language required outside tourist areas"],
    avgTemp: "20°C / 68°F",
    timeZone: "CET (UTC+1/+2)",
  },
  mexico: {
    name: "Mexico",
    flag: "🇲🇽",
    code: "MX",
    region: "Latin America",
    cities: ["Mexico City (CDMX)", "Oaxaca", "Mérida", "San Miguel de Allende", "Puerto Vallarta"],
    visaTypes: ["Temporary Resident Visa", "Permanent Resident Visa", "180-day tourist stay"],
    costRange: { min: 1200, max: 2800 },
    safetyRating: 6.5,
    healthcareQuality: 7.0,
    expatFriendliness: 8.5,
    climate: "warm",
    language: "Spanish (English in expat hubs)",
    internetSpeed: "Moderate",
    taxFriendly: true,
    highlights: ["Close to US", "Low cost of living", "Vibrant culture", "Great food"],
    challenges: ["Safety varies by region", "Spanish needed", "Infrastructure gaps"],
    avgTemp: "22°C / 72°F",
    timeZone: "CST/EST (UTC-6 to -5)",
  },
  thailand: {
    name: "Thailand",
    flag: "🇹🇭",
    code: "TH",
    region: "Asia",
    cities: ["Chiang Mai", "Bangkok", "Phuket", "Koh Samui", "Hua Hin"],
    visaTypes: ["LTR Visa (Long-Term Resident)", "Thailand Elite Visa", "SMART Visa", "Tourist Visa + Border Run"],
    costRange: { min: 1000, max: 2500 },
    safetyRating: 7.8,
    healthcareQuality: 8.2,
    expatFriendliness: 8.9,
    climate: "warm",
    language: "Thai (English in tourist areas)",
    internetSpeed: "Fast",
    taxFriendly: true,
    highlights: ["Ultra low cost of living", "Amazing food", "Digital nomad hubs", "World-class healthcare"],
    challenges: ["Visa complexity", "Language barrier", "Political instability history"],
    avgTemp: "28°C / 82°F",
    timeZone: "ICT (UTC+7)",
  },
  costarica: {
    name: "Costa Rica",
    flag: "🇨🇷",
    code: "CR",
    region: "Latin America",
    cities: ["San José", "Tamarindo", "Jacó", "Nosara", "La Fortuna"],
    visaTypes: ["Pensionado Visa", "Rentista Visa", "Digital Nomad Visa", "Investor Visa"],
    costRange: { min: 1500, max: 3200 },
    safetyRating: 8.0,
    healthcareQuality: 8.0,
    expatFriendliness: 9.0,
    climate: "warm",
    language: "Spanish (English in tourist areas)",
    internetSpeed: "Moderate",
    taxFriendly: true,
    highlights: ["Stable democracy", "Nature & biodiversity", "Pura Vida lifestyle", "Good healthcare"],
    challenges: ["Higher cost than other LATAM", "Infrastructure issues", "Rainy season"],
    avgTemp: "24°C / 75°F",
    timeZone: "CST (UTC-6)",
  },
  germany: {
    name: "Germany",
    flag: "🇩🇪",
    code: "DE",
    region: "Europe",
    cities: ["Berlin", "Munich", "Hamburg", "Leipzig", "Stuttgart"],
    visaTypes: ["Freelancer Visa", "Job Seeker Visa", "EU Blue Card", "Opportunity Card"],
    costRange: { min: 2500, max: 5000 },
    safetyRating: 9.5,
    healthcareQuality: 9.5,
    expatFriendliness: 8.0,
    climate: "cold",
    language: "German (English in cities)",
    internetSpeed: "Fast",
    taxFriendly: false,
    highlights: ["World-class healthcare", "Strong infrastructure", "EU access", "Tech hub"],
    challenges: ["High taxes", "German language needed", "Cold winters", "High cost of living"],
    avgTemp: "10°C / 50°F",
    timeZone: "CET (UTC+1/+2)",
  },
  georgia: {
    name: "Georgia",
    flag: "🇬🇪",
    code: "GE",
    region: "Europe",
    cities: ["Tbilisi", "Batumi", "Kutaisi", "Gudauri"],
    visaTypes: ["365-day visa-free stay", "Permanent Residency", "Work Permit", "Virtual Zone Status (Tax Free)"],
    costRange: { min: 800, max: 2000 },
    safetyRating: 8.5,
    healthcareQuality: 7.0,
    expatFriendliness: 9.2,
    climate: "mild",
    language: "Georgian (English in Tbilisi)",
    internetSpeed: "Fast",
    taxFriendly: true,
    highlights: ["Visa-free 1 year", "Ultra low taxes", "Low cost of living", "Growing expat scene"],
    challenges: ["Healthcare improving but developing", "Language barrier", "Limited nightlife outside Tbilisi"],
    avgTemp: "14°C / 57°F",
    timeZone: "GET (UTC+4)",
  },
  colombia: {
    name: "Colombia",
    flag: "🇨🇴",
    code: "CO",
    region: "Latin America",
    cities: ["Medellín", "Bogotá", "Cartagena", "Santa Marta", "Cali"],
    visaTypes: ["Digital Nomad Visa (V)", "Investor Visa (M)", "Pensioner Visa (R)", "180-day tourist stay"],
    costRange: { min: 1000, max: 2500 },
    safetyRating: 7.0,
    healthcareQuality: 7.8,
    expatFriendliness: 8.8,
    climate: "mild",
    language: "Spanish (English in Medellín expat areas)",
    internetSpeed: "Moderate",
    taxFriendly: true,
    highlights: ["Eternal spring climate", "Low cost of living", "Vibrant culture", "Booming expat scene"],
    challenges: ["Safety perception gap", "Spanish required", "Altitude adjustment in Bogotá"],
    avgTemp: "22°C / 72°F (Medellín)",
    timeZone: "COT (UTC-5)",
  },
}

export type CountryKey = keyof typeof countryData
export type Country = typeof countryData[CountryKey]
